version: "3.9"

services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 1245!

  web:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test!12@
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1245!
      ME_CONFIG_MONGODB_SERVER: db